[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = []

[project]
name = "libsymtorch"
version = "0.2.5"
authors = [
  { name="Ibrahim H.I. Abushawish", email="ibrahim.hamed2701@gmail.com" },
]
description = "DEPRECATED: This package has been renamed to torchsympy"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
  "torchsympy>=0.3.0",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Mathematics",
]

[project.urls]
"Homepage" = "https://github.com/ibeuler/TorchSymPy"